// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "InteractWordV2.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://github.com/SocialSisterYi/bilibili-API-collect/issues/1332#issuecomment-3046115843
 *
 * @generated from protobuf message InteractWordV2
 */
export interface InteractWordV2 {
    /**
     * @generated from protobuf field: uint64 uid = 1
     */
    uid: bigint;
    /**
     * @generated from protobuf field: string uname = 2
     */
    uname: string;
    /**
     * @generated from protobuf field: InteractWordV2.MsgType msg_type = 5
     */
    msgType: InteractWordV2_MsgType;
    /**
     * @generated from protobuf field: uint32 room_id = 6
     */
    roomId: number;
    /**
     * @generated from protobuf field: uint32 timestamp = 7
     */
    timestamp: number; // second
    /**
     * @generated from protobuf field: uint64 score = 8
     */
    score: bigint;
    /**
     * @generated from protobuf field: optional InteractWordV2.FansMedal fans_medal = 9
     */
    fansMedal?: InteractWordV2_FansMedal;
    /**
     * @generated from protobuf field: InteractWordV2.RankInfo rank_info = 12
     */
    rankInfo?: InteractWordV2_RankInfo;
    /**
     * @generated from protobuf field: uint64 trigger_time = 15
     */
    triggerTime: bigint; // maybe
    /**
     * @generated from protobuf field: optional uint32 guard_level = 16
     */
    guardLevel?: number; // 可能对应INTERACT_WORD中的privilege_type
    /**
     * @generated from protobuf field: optional uint32 daily_rank = 17
     */
    dailyRank?: number;
    /**
     * @generated from protobuf field: InteractWordV2.UserInfo uinfo = 22
     */
    uinfo?: InteractWordV2_UserInfo;
}
/**
 * @generated from protobuf message InteractWordV2.FansMedal
 */
export interface InteractWordV2_FansMedal {
    /**
     * @generated from protobuf field: uint64 target_id = 1
     */
    targetId: bigint; // also named anchor_id or ruid
    /**
     * @generated from protobuf field: uint32 medal_level = 2
     */
    medalLevel: number;
    /**
     * @generated from protobuf field: string medal_name = 3
     */
    medalName: string;
    /**
     * @generated from protobuf field: uint32 color = 4
     */
    color: number;
    /**
     * @generated from protobuf field: uint32 color_start = 5
     */
    colorStart: number;
    /**
     * @generated from protobuf field: uint32 color_end = 6
     */
    colorEnd: number;
    /**
     * @generated from protobuf field: uint32 color_border = 7
     */
    colorBorder: number;
    /**
     * @generated from protobuf field: optional uint32 is_lighted = 8
     */
    isLighted?: number;
    /**
     * @generated from protobuf field: optional uint32 guard_level = 9
     */
    guardLevel?: number;
    /**
     * @generated from protobuf field: uint32 room_id = 12
     */
    roomId: number;
    /**
     * @generated from protobuf field: uint32 score = 13
     */
    score: number;
}
/**
 * @generated from protobuf message InteractWordV2.RankInfo
 */
export interface InteractWordV2_RankInfo {
    /**
     * @generated from protobuf field: uint32 rank = 1
     */
    rank: number;
}
// 19: 排行榜信息
// message DailyRankInfo {
//     uint32 rank = 1;
//     string key = 2;
//     string description = 3;
// }
// optional DaylyRankInfo daily_rank_info = 19;

/**
 * @generated from protobuf message InteractWordV2.UserInfo
 */
export interface InteractWordV2_UserInfo {
    /**
     * @generated from protobuf field: uint64 uid = 1
     */
    uid: bigint;
    /**
     * @generated from protobuf field: InteractWordV2.UserInfo.BaseInfo base = 2
     */
    base?: InteractWordV2_UserInfo_BaseInfo;
    /**
     * @generated from protobuf field: optional InteractWordV2.UserInfo.MedalInfo medal_info = 3
     */
    medalInfo?: InteractWordV2_UserInfo_MedalInfo;
    /**
     * @generated from protobuf field: optional InteractWordV2.UserInfo.WealthInfo wealth = 4
     */
    wealth?: InteractWordV2_UserInfo_WealthInfo;
    /**
     * @generated from protobuf field: optional InteractWordV2.UserInfo.GuardInfo guard = 6
     */
    guard?: InteractWordV2_UserInfo_GuardInfo;
}
/**
 * @generated from protobuf message InteractWordV2.UserInfo.BaseInfo
 */
export interface InteractWordV2_UserInfo_BaseInfo {
    /**
     * @generated from protobuf field: string uname = 1
     */
    uname: string;
    /**
     * @generated from protobuf field: string face = 2
     */
    face: string;
    /**
     * @generated from protobuf field: optional InteractWordV2.UserInfo.BaseInfo.OriginInfo origin_info = 6
     */
    originInfo?: InteractWordV2_UserInfo_BaseInfo_OriginInfo;
    /**
     * message OnlyGodKnow_1 {
     *    uint64 i_dont_know = 4;
     * }
     * optional OnlyGodKnow_1 only_god_know = 7;
     *
     * @generated from protobuf field: optional string name_color_str = 8
     */
    nameColorStr?: string; // username color showed in danmaku
}
/**
 * @generated from protobuf message InteractWordV2.UserInfo.BaseInfo.OriginInfo
 */
export interface InteractWordV2_UserInfo_BaseInfo_OriginInfo {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string face = 2
     */
    face: string;
}
/**
 * @generated from protobuf message InteractWordV2.UserInfo.MedalInfo
 */
export interface InteractWordV2_UserInfo_MedalInfo {
    /**
     * @generated from protobuf field: string medal_name = 1
     */
    medalName: string;
    /**
     * @generated from protobuf field: uint32 medal_level = 2
     */
    medalLevel: number;
    /**
     * @generated from protobuf field: uint32 color_start = 3
     */
    colorStart: number;
    /**
     * @generated from protobuf field: uint32 color_end = 4
     */
    colorEnd: number;
    /**
     * @generated from protobuf field: uint32 color_border = 5
     */
    colorBorder: number;
    /**
     * @generated from protobuf field: uint32 color = 6
     */
    color: number;
    /**
     * @generated from protobuf field: uint32 id = 7
     */
    id: number; // I don't know what is this
    /**
     * @generated from protobuf field: uint32 is_lighted = 9
     */
    isLighted: number;
    /**
     * @generated from protobuf field: uint64 ruid = 10
     */
    ruid: bigint; // also named target_id or anchor_id
    /**
     * @generated from protobuf field: uint32 guard_level = 11
     */
    guardLevel: number;
    /**
     * @generated from protobuf field: uint32 score = 12
     */
    score: number;
    /**
     * @generated from protobuf field: string guard_icon = 13
     */
    guardIcon: string;
    /**
     * @generated from protobuf field: string v2_medal_color_start = 15
     */
    v2MedalColorStart: string;
    /**
     * @generated from protobuf field: string v2_medal_color_end = 16
     */
    v2MedalColorEnd: string;
    /**
     * @generated from protobuf field: string v2_medal_color_border = 17
     */
    v2MedalColorBorder: string;
    /**
     * @generated from protobuf field: string v2_medal_color_text = 18
     */
    v2MedalColorText: string;
    /**
     * @generated from protobuf field: string v2_medal_color_level = 19
     */
    v2MedalColorLevel: string;
}
/**
 * @generated from protobuf message InteractWordV2.UserInfo.WealthInfo
 */
export interface InteractWordV2_UserInfo_WealthInfo {
    /**
     * @generated from protobuf field: uint32 level = 1
     */
    level: number;
}
/**
 * @generated from protobuf message InteractWordV2.UserInfo.GuardInfo
 */
export interface InteractWordV2_UserInfo_GuardInfo {
    /**
     * @generated from protobuf field: uint32 level = 1
     */
    level: number;
    /**
     * @generated from protobuf field: string expired_str = 2
     */
    expiredStr: string;
}
/**
 * @generated from protobuf enum InteractWordV2.MsgType
 */
export enum InteractWordV2_MsgType {
    /**
     * @generated from protobuf enum value: MSG_UNKNOWN = 0;
     */
    MSG_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: MSG_ENTER_ROOM = 1;
     */
    MSG_ENTER_ROOM = 1,
    /**
     * @generated from protobuf enum value: MSG_FOLLOW = 2;
     */
    MSG_FOLLOW = 2,
    /**
     * @generated from protobuf enum value: MSG_SHARE_ROOM = 3;
     */
    MSG_SHARE_ROOM = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2$Type extends MessageType<InteractWordV2> {
    constructor() {
        super("InteractWordV2", [
            { no: 1, name: "uid", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "uname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "msg_type", kind: "enum", T: () => ["InteractWordV2.MsgType", InteractWordV2_MsgType] },
            { no: 6, name: "room_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "timestamp", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "score", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 9, name: "fans_medal", kind: "message", T: () => InteractWordV2_FansMedal },
            { no: 12, name: "rank_info", kind: "message", T: () => InteractWordV2_RankInfo },
            { no: 15, name: "trigger_time", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 16, name: "guard_level", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 17, name: "daily_rank", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 22, name: "uinfo", kind: "message", T: () => InteractWordV2_UserInfo }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2>): InteractWordV2 {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uid = 0n;
        message.uname = "";
        message.msgType = 0;
        message.roomId = 0;
        message.timestamp = 0;
        message.score = 0n;
        message.triggerTime = 0n;
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2): InteractWordV2 {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 uid */ 1:
                    message.uid = reader.uint64().toBigInt();
                    break;
                case /* string uname */ 2:
                    message.uname = reader.string();
                    break;
                case /* InteractWordV2.MsgType msg_type */ 5:
                    message.msgType = reader.int32();
                    break;
                case /* uint32 room_id */ 6:
                    message.roomId = reader.uint32();
                    break;
                case /* uint32 timestamp */ 7:
                    message.timestamp = reader.uint32();
                    break;
                case /* uint64 score */ 8:
                    message.score = reader.uint64().toBigInt();
                    break;
                case /* optional InteractWordV2.FansMedal fans_medal */ 9:
                    message.fansMedal = InteractWordV2_FansMedal.internalBinaryRead(reader, reader.uint32(), options, message.fansMedal);
                    break;
                case /* InteractWordV2.RankInfo rank_info */ 12:
                    message.rankInfo = InteractWordV2_RankInfo.internalBinaryRead(reader, reader.uint32(), options, message.rankInfo);
                    break;
                case /* uint64 trigger_time */ 15:
                    message.triggerTime = reader.uint64().toBigInt();
                    break;
                case /* optional uint32 guard_level */ 16:
                    message.guardLevel = reader.uint32();
                    break;
                case /* optional uint32 daily_rank */ 17:
                    message.dailyRank = reader.uint32();
                    break;
                case /* InteractWordV2.UserInfo uinfo */ 22:
                    message.uinfo = InteractWordV2_UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.uinfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 uid = 1; */
        if (message.uid !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.uid);
        /* string uname = 2; */
        if (message.uname !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uname);
        /* InteractWordV2.MsgType msg_type = 5; */
        if (message.msgType !== 0)
            writer.tag(5, WireType.Varint).int32(message.msgType);
        /* uint32 room_id = 6; */
        if (message.roomId !== 0)
            writer.tag(6, WireType.Varint).uint32(message.roomId);
        /* uint32 timestamp = 7; */
        if (message.timestamp !== 0)
            writer.tag(7, WireType.Varint).uint32(message.timestamp);
        /* uint64 score = 8; */
        if (message.score !== 0n)
            writer.tag(8, WireType.Varint).uint64(message.score);
        /* optional InteractWordV2.FansMedal fans_medal = 9; */
        if (message.fansMedal)
            InteractWordV2_FansMedal.internalBinaryWrite(message.fansMedal, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* InteractWordV2.RankInfo rank_info = 12; */
        if (message.rankInfo)
            InteractWordV2_RankInfo.internalBinaryWrite(message.rankInfo, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* uint64 trigger_time = 15; */
        if (message.triggerTime !== 0n)
            writer.tag(15, WireType.Varint).uint64(message.triggerTime);
        /* optional uint32 guard_level = 16; */
        if (message.guardLevel !== undefined)
            writer.tag(16, WireType.Varint).uint32(message.guardLevel);
        /* optional uint32 daily_rank = 17; */
        if (message.dailyRank !== undefined)
            writer.tag(17, WireType.Varint).uint32(message.dailyRank);
        /* InteractWordV2.UserInfo uinfo = 22; */
        if (message.uinfo)
            InteractWordV2_UserInfo.internalBinaryWrite(message.uinfo, writer.tag(22, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2
 */
export const InteractWordV2 = new InteractWordV2$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_FansMedal$Type extends MessageType<InteractWordV2_FansMedal> {
    constructor() {
        super("InteractWordV2.FansMedal", [
            { no: 1, name: "target_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "medal_level", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "medal_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "color", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "color_start", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "color_end", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "color_border", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "is_lighted", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "guard_level", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 12, name: "room_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 13, name: "score", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_FansMedal>): InteractWordV2_FansMedal {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.targetId = 0n;
        message.medalLevel = 0;
        message.medalName = "";
        message.color = 0;
        message.colorStart = 0;
        message.colorEnd = 0;
        message.colorBorder = 0;
        message.roomId = 0;
        message.score = 0;
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_FansMedal>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_FansMedal): InteractWordV2_FansMedal {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 target_id */ 1:
                    message.targetId = reader.uint64().toBigInt();
                    break;
                case /* uint32 medal_level */ 2:
                    message.medalLevel = reader.uint32();
                    break;
                case /* string medal_name */ 3:
                    message.medalName = reader.string();
                    break;
                case /* uint32 color */ 4:
                    message.color = reader.uint32();
                    break;
                case /* uint32 color_start */ 5:
                    message.colorStart = reader.uint32();
                    break;
                case /* uint32 color_end */ 6:
                    message.colorEnd = reader.uint32();
                    break;
                case /* uint32 color_border */ 7:
                    message.colorBorder = reader.uint32();
                    break;
                case /* optional uint32 is_lighted */ 8:
                    message.isLighted = reader.uint32();
                    break;
                case /* optional uint32 guard_level */ 9:
                    message.guardLevel = reader.uint32();
                    break;
                case /* uint32 room_id */ 12:
                    message.roomId = reader.uint32();
                    break;
                case /* uint32 score */ 13:
                    message.score = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_FansMedal, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 target_id = 1; */
        if (message.targetId !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.targetId);
        /* uint32 medal_level = 2; */
        if (message.medalLevel !== 0)
            writer.tag(2, WireType.Varint).uint32(message.medalLevel);
        /* string medal_name = 3; */
        if (message.medalName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.medalName);
        /* uint32 color = 4; */
        if (message.color !== 0)
            writer.tag(4, WireType.Varint).uint32(message.color);
        /* uint32 color_start = 5; */
        if (message.colorStart !== 0)
            writer.tag(5, WireType.Varint).uint32(message.colorStart);
        /* uint32 color_end = 6; */
        if (message.colorEnd !== 0)
            writer.tag(6, WireType.Varint).uint32(message.colorEnd);
        /* uint32 color_border = 7; */
        if (message.colorBorder !== 0)
            writer.tag(7, WireType.Varint).uint32(message.colorBorder);
        /* optional uint32 is_lighted = 8; */
        if (message.isLighted !== undefined)
            writer.tag(8, WireType.Varint).uint32(message.isLighted);
        /* optional uint32 guard_level = 9; */
        if (message.guardLevel !== undefined)
            writer.tag(9, WireType.Varint).uint32(message.guardLevel);
        /* uint32 room_id = 12; */
        if (message.roomId !== 0)
            writer.tag(12, WireType.Varint).uint32(message.roomId);
        /* uint32 score = 13; */
        if (message.score !== 0)
            writer.tag(13, WireType.Varint).uint32(message.score);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.FansMedal
 */
export const InteractWordV2_FansMedal = new InteractWordV2_FansMedal$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_RankInfo$Type extends MessageType<InteractWordV2_RankInfo> {
    constructor() {
        super("InteractWordV2.RankInfo", [
            { no: 1, name: "rank", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_RankInfo>): InteractWordV2_RankInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rank = 0;
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_RankInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_RankInfo): InteractWordV2_RankInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 rank */ 1:
                    message.rank = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_RankInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 rank = 1; */
        if (message.rank !== 0)
            writer.tag(1, WireType.Varint).uint32(message.rank);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.RankInfo
 */
export const InteractWordV2_RankInfo = new InteractWordV2_RankInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_UserInfo$Type extends MessageType<InteractWordV2_UserInfo> {
    constructor() {
        super("InteractWordV2.UserInfo", [
            { no: 1, name: "uid", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "base", kind: "message", T: () => InteractWordV2_UserInfo_BaseInfo },
            { no: 3, name: "medal_info", kind: "message", T: () => InteractWordV2_UserInfo_MedalInfo },
            { no: 4, name: "wealth", kind: "message", T: () => InteractWordV2_UserInfo_WealthInfo },
            { no: 6, name: "guard", kind: "message", T: () => InteractWordV2_UserInfo_GuardInfo }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_UserInfo>): InteractWordV2_UserInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uid = 0n;
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_UserInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_UserInfo): InteractWordV2_UserInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 uid */ 1:
                    message.uid = reader.uint64().toBigInt();
                    break;
                case /* InteractWordV2.UserInfo.BaseInfo base */ 2:
                    message.base = InteractWordV2_UserInfo_BaseInfo.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* optional InteractWordV2.UserInfo.MedalInfo medal_info */ 3:
                    message.medalInfo = InteractWordV2_UserInfo_MedalInfo.internalBinaryRead(reader, reader.uint32(), options, message.medalInfo);
                    break;
                case /* optional InteractWordV2.UserInfo.WealthInfo wealth */ 4:
                    message.wealth = InteractWordV2_UserInfo_WealthInfo.internalBinaryRead(reader, reader.uint32(), options, message.wealth);
                    break;
                case /* optional InteractWordV2.UserInfo.GuardInfo guard */ 6:
                    message.guard = InteractWordV2_UserInfo_GuardInfo.internalBinaryRead(reader, reader.uint32(), options, message.guard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_UserInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 uid = 1; */
        if (message.uid !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.uid);
        /* InteractWordV2.UserInfo.BaseInfo base = 2; */
        if (message.base)
            InteractWordV2_UserInfo_BaseInfo.internalBinaryWrite(message.base, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional InteractWordV2.UserInfo.MedalInfo medal_info = 3; */
        if (message.medalInfo)
            InteractWordV2_UserInfo_MedalInfo.internalBinaryWrite(message.medalInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional InteractWordV2.UserInfo.WealthInfo wealth = 4; */
        if (message.wealth)
            InteractWordV2_UserInfo_WealthInfo.internalBinaryWrite(message.wealth, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional InteractWordV2.UserInfo.GuardInfo guard = 6; */
        if (message.guard)
            InteractWordV2_UserInfo_GuardInfo.internalBinaryWrite(message.guard, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.UserInfo
 */
export const InteractWordV2_UserInfo = new InteractWordV2_UserInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_UserInfo_BaseInfo$Type extends MessageType<InteractWordV2_UserInfo_BaseInfo> {
    constructor() {
        super("InteractWordV2.UserInfo.BaseInfo", [
            { no: 1, name: "uname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "face", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "origin_info", kind: "message", T: () => InteractWordV2_UserInfo_BaseInfo_OriginInfo },
            { no: 8, name: "name_color_str", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_UserInfo_BaseInfo>): InteractWordV2_UserInfo_BaseInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uname = "";
        message.face = "";
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_UserInfo_BaseInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_UserInfo_BaseInfo): InteractWordV2_UserInfo_BaseInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uname */ 1:
                    message.uname = reader.string();
                    break;
                case /* string face */ 2:
                    message.face = reader.string();
                    break;
                case /* optional InteractWordV2.UserInfo.BaseInfo.OriginInfo origin_info */ 6:
                    message.originInfo = InteractWordV2_UserInfo_BaseInfo_OriginInfo.internalBinaryRead(reader, reader.uint32(), options, message.originInfo);
                    break;
                case /* optional string name_color_str */ 8:
                    message.nameColorStr = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_UserInfo_BaseInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uname = 1; */
        if (message.uname !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uname);
        /* string face = 2; */
        if (message.face !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.face);
        /* optional InteractWordV2.UserInfo.BaseInfo.OriginInfo origin_info = 6; */
        if (message.originInfo)
            InteractWordV2_UserInfo_BaseInfo_OriginInfo.internalBinaryWrite(message.originInfo, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional string name_color_str = 8; */
        if (message.nameColorStr !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.nameColorStr);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.UserInfo.BaseInfo
 */
export const InteractWordV2_UserInfo_BaseInfo = new InteractWordV2_UserInfo_BaseInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_UserInfo_BaseInfo_OriginInfo$Type extends MessageType<InteractWordV2_UserInfo_BaseInfo_OriginInfo> {
    constructor() {
        super("InteractWordV2.UserInfo.BaseInfo.OriginInfo", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "face", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_UserInfo_BaseInfo_OriginInfo>): InteractWordV2_UserInfo_BaseInfo_OriginInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.face = "";
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_UserInfo_BaseInfo_OriginInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_UserInfo_BaseInfo_OriginInfo): InteractWordV2_UserInfo_BaseInfo_OriginInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string face */ 2:
                    message.face = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_UserInfo_BaseInfo_OriginInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string face = 2; */
        if (message.face !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.face);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.UserInfo.BaseInfo.OriginInfo
 */
export const InteractWordV2_UserInfo_BaseInfo_OriginInfo = new InteractWordV2_UserInfo_BaseInfo_OriginInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_UserInfo_MedalInfo$Type extends MessageType<InteractWordV2_UserInfo_MedalInfo> {
    constructor() {
        super("InteractWordV2.UserInfo.MedalInfo", [
            { no: 1, name: "medal_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "medal_level", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "color_start", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "color_end", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "color_border", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "color", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "is_lighted", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "ruid", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 11, name: "guard_level", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 12, name: "score", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 13, name: "guard_icon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "v2_medal_color_start", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "v2_medal_color_end", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "v2_medal_color_border", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "v2_medal_color_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "v2_medal_color_level", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_UserInfo_MedalInfo>): InteractWordV2_UserInfo_MedalInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.medalName = "";
        message.medalLevel = 0;
        message.colorStart = 0;
        message.colorEnd = 0;
        message.colorBorder = 0;
        message.color = 0;
        message.id = 0;
        message.isLighted = 0;
        message.ruid = 0n;
        message.guardLevel = 0;
        message.score = 0;
        message.guardIcon = "";
        message.v2MedalColorStart = "";
        message.v2MedalColorEnd = "";
        message.v2MedalColorBorder = "";
        message.v2MedalColorText = "";
        message.v2MedalColorLevel = "";
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_UserInfo_MedalInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_UserInfo_MedalInfo): InteractWordV2_UserInfo_MedalInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string medal_name */ 1:
                    message.medalName = reader.string();
                    break;
                case /* uint32 medal_level */ 2:
                    message.medalLevel = reader.uint32();
                    break;
                case /* uint32 color_start */ 3:
                    message.colorStart = reader.uint32();
                    break;
                case /* uint32 color_end */ 4:
                    message.colorEnd = reader.uint32();
                    break;
                case /* uint32 color_border */ 5:
                    message.colorBorder = reader.uint32();
                    break;
                case /* uint32 color */ 6:
                    message.color = reader.uint32();
                    break;
                case /* uint32 id */ 7:
                    message.id = reader.uint32();
                    break;
                case /* uint32 is_lighted */ 9:
                    message.isLighted = reader.uint32();
                    break;
                case /* uint64 ruid */ 10:
                    message.ruid = reader.uint64().toBigInt();
                    break;
                case /* uint32 guard_level */ 11:
                    message.guardLevel = reader.uint32();
                    break;
                case /* uint32 score */ 12:
                    message.score = reader.uint32();
                    break;
                case /* string guard_icon */ 13:
                    message.guardIcon = reader.string();
                    break;
                case /* string v2_medal_color_start */ 15:
                    message.v2MedalColorStart = reader.string();
                    break;
                case /* string v2_medal_color_end */ 16:
                    message.v2MedalColorEnd = reader.string();
                    break;
                case /* string v2_medal_color_border */ 17:
                    message.v2MedalColorBorder = reader.string();
                    break;
                case /* string v2_medal_color_text */ 18:
                    message.v2MedalColorText = reader.string();
                    break;
                case /* string v2_medal_color_level */ 19:
                    message.v2MedalColorLevel = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_UserInfo_MedalInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string medal_name = 1; */
        if (message.medalName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.medalName);
        /* uint32 medal_level = 2; */
        if (message.medalLevel !== 0)
            writer.tag(2, WireType.Varint).uint32(message.medalLevel);
        /* uint32 color_start = 3; */
        if (message.colorStart !== 0)
            writer.tag(3, WireType.Varint).uint32(message.colorStart);
        /* uint32 color_end = 4; */
        if (message.colorEnd !== 0)
            writer.tag(4, WireType.Varint).uint32(message.colorEnd);
        /* uint32 color_border = 5; */
        if (message.colorBorder !== 0)
            writer.tag(5, WireType.Varint).uint32(message.colorBorder);
        /* uint32 color = 6; */
        if (message.color !== 0)
            writer.tag(6, WireType.Varint).uint32(message.color);
        /* uint32 id = 7; */
        if (message.id !== 0)
            writer.tag(7, WireType.Varint).uint32(message.id);
        /* uint32 is_lighted = 9; */
        if (message.isLighted !== 0)
            writer.tag(9, WireType.Varint).uint32(message.isLighted);
        /* uint64 ruid = 10; */
        if (message.ruid !== 0n)
            writer.tag(10, WireType.Varint).uint64(message.ruid);
        /* uint32 guard_level = 11; */
        if (message.guardLevel !== 0)
            writer.tag(11, WireType.Varint).uint32(message.guardLevel);
        /* uint32 score = 12; */
        if (message.score !== 0)
            writer.tag(12, WireType.Varint).uint32(message.score);
        /* string guard_icon = 13; */
        if (message.guardIcon !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.guardIcon);
        /* string v2_medal_color_start = 15; */
        if (message.v2MedalColorStart !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.v2MedalColorStart);
        /* string v2_medal_color_end = 16; */
        if (message.v2MedalColorEnd !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.v2MedalColorEnd);
        /* string v2_medal_color_border = 17; */
        if (message.v2MedalColorBorder !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.v2MedalColorBorder);
        /* string v2_medal_color_text = 18; */
        if (message.v2MedalColorText !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.v2MedalColorText);
        /* string v2_medal_color_level = 19; */
        if (message.v2MedalColorLevel !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.v2MedalColorLevel);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.UserInfo.MedalInfo
 */
export const InteractWordV2_UserInfo_MedalInfo = new InteractWordV2_UserInfo_MedalInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_UserInfo_WealthInfo$Type extends MessageType<InteractWordV2_UserInfo_WealthInfo> {
    constructor() {
        super("InteractWordV2.UserInfo.WealthInfo", [
            { no: 1, name: "level", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_UserInfo_WealthInfo>): InteractWordV2_UserInfo_WealthInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.level = 0;
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_UserInfo_WealthInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_UserInfo_WealthInfo): InteractWordV2_UserInfo_WealthInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 level */ 1:
                    message.level = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_UserInfo_WealthInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 level = 1; */
        if (message.level !== 0)
            writer.tag(1, WireType.Varint).uint32(message.level);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.UserInfo.WealthInfo
 */
export const InteractWordV2_UserInfo_WealthInfo = new InteractWordV2_UserInfo_WealthInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InteractWordV2_UserInfo_GuardInfo$Type extends MessageType<InteractWordV2_UserInfo_GuardInfo> {
    constructor() {
        super("InteractWordV2.UserInfo.GuardInfo", [
            { no: 1, name: "level", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "expired_str", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InteractWordV2_UserInfo_GuardInfo>): InteractWordV2_UserInfo_GuardInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.level = 0;
        message.expiredStr = "";
        if (value !== undefined)
            reflectionMergePartial<InteractWordV2_UserInfo_GuardInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InteractWordV2_UserInfo_GuardInfo): InteractWordV2_UserInfo_GuardInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 level */ 1:
                    message.level = reader.uint32();
                    break;
                case /* string expired_str */ 2:
                    message.expiredStr = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InteractWordV2_UserInfo_GuardInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 level = 1; */
        if (message.level !== 0)
            writer.tag(1, WireType.Varint).uint32(message.level);
        /* string expired_str = 2; */
        if (message.expiredStr !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.expiredStr);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message InteractWordV2.UserInfo.GuardInfo
 */
export const InteractWordV2_UserInfo_GuardInfo = new InteractWordV2_UserInfo_GuardInfo$Type();
