/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter eslint_disable
// @generated from protobuf file "OnlineRankV3.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// https://github.com/SocialSisterYi/bilibili-API-collect/issues/1332#issuecomment-3055621742

/**
 * @generated from protobuf message AccountInfo
 */
export interface AccountInfo {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string face = 2
     */
    face: string;
}
/**
 * @generated from protobuf message Base
 */
export interface Base {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string face = 2
     */
    face: string;
    /**
     * @generated from protobuf field: int32 name_color = 3
     */
    nameColor: number;
    /**
     * @generated from protobuf field: bool is_mystery = 4
     */
    isMystery: boolean;
    /**
     * @generated from protobuf field: RiskCtrlInfo risk_ctrl_info = 5
     */
    riskCtrlInfo?: RiskCtrlInfo;
    /**
     * @generated from protobuf field: AccountInfo origin_info = 6
     */
    originInfo?: AccountInfo;
    /**
     * @generated from protobuf field: OfficialInfo official_info = 7
     */
    officialInfo?: OfficialInfo;
    /**
     * @generated from protobuf field: string name_color_str = 8
     */
    nameColorStr: string;
}
/**
 * @generated from protobuf message BaseOption
 */
export interface BaseOption {
    /**
     * @generated from protobuf field: bool need_mystery = 1
     */
    needMystery: boolean;
    /**
     * @generated from protobuf field: RiskCtrl risk_ctrl = 2
     */
    riskCtrl?: RiskCtrl;
    /**
     * @generated from protobuf field: RoomAnonCtrl room_anon_ctrl = 3
     */
    roomAnonCtrl?: RoomAnonCtrl;
    /**
     * @generated from protobuf field: repeated int32 risk_ctrl_handles = 4
     */
    riskCtrlHandles: number[];
}
/**
 * @generated from protobuf message Guard
 */
export interface Guard {
    /**
     * @generated from protobuf field: int64 level = 1
     */
    level: bigint;
    /**
     * @generated from protobuf field: string expired_str = 2
     */
    expiredStr: string;
}
/**
 * @generated from protobuf message GuardLeader
 */
export interface GuardLeader {
    /**
     * @generated from protobuf field: bool is_guard_leader = 1
     */
    isGuardLeader: boolean;
}
/**
 * @generated from protobuf message GuardLeaderOption
 */
export interface GuardLeaderOption {
    /**
     * @generated from protobuf field: int64 ruid = 1
     */
    ruid: bigint;
    /**
     * @generated from protobuf field: int64 room_id = 2
     */
    roomId: bigint;
}
/**
 * @generated from protobuf message GuardOption
 */
export interface GuardOption {
    /**
     * @generated from protobuf field: int64 ruid = 1
     */
    ruid: bigint;
    /**
     * @generated from protobuf field: bool use_local_cache = 2
     */
    useLocalCache: boolean;
    /**
     * @generated from protobuf field: bool strong_depend = 3
     */
    strongDepend: boolean;
}
/**
 * @generated from protobuf message Medal
 */
export interface Medal {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: int64 level = 2
     */
    level: bigint;
    /**
     * @generated from protobuf field: int64 color_start = 3
     */
    colorStart: bigint;
    /**
     * @generated from protobuf field: int64 color_end = 4
     */
    colorEnd: bigint;
    /**
     * @generated from protobuf field: int64 color_border = 5
     */
    colorBorder: bigint;
    /**
     * @generated from protobuf field: int64 color = 6
     */
    color: bigint;
    /**
     * @generated from protobuf field: int64 id = 7
     */
    id: bigint;
    /**
     * @generated from protobuf field: HaveMedalType typ = 8
     */
    typ: HaveMedalType;
    /**
     * @generated from protobuf field: int64 is_light = 9
     */
    isLight: bigint;
    /**
     * @generated from protobuf field: int64 ruid = 10
     */
    ruid: bigint;
    /**
     * @generated from protobuf field: int64 guard_level = 11
     */
    guardLevel: bigint;
    /**
     * @generated from protobuf field: int64 score = 12
     */
    score: bigint;
    /**
     * @generated from protobuf field: string guard_icon = 13
     */
    guardIcon: string;
    /**
     * @generated from protobuf field: string honor_icon = 14
     */
    honorIcon: string;
    /**
     * @generated from protobuf field: string v2_medal_color_start = 15
     */
    v2MedalColorStart: string;
    /**
     * @generated from protobuf field: string v2_medal_color_end = 16
     */
    v2MedalColorEnd: string;
    /**
     * @generated from protobuf field: string v2_medal_color_border = 17
     */
    v2MedalColorBorder: string;
    /**
     * @generated from protobuf field: string v2_medal_color_text = 18
     */
    v2MedalColorText: string;
    /**
     * @generated from protobuf field: string v2_medal_color_level = 19
     */
    v2MedalColorLevel: string;
    /**
     * @generated from protobuf field: int64 user_receive_count = 20
     */
    userReceiveCount: bigint;
}
/**
 * @generated from protobuf message MedalOption
 */
export interface MedalOption {
    /**
     * @generated from protobuf field: MedalType typ = 1
     */
    typ: MedalType;
    /**
     * @generated from protobuf field: int64 ruid = 2
     */
    ruid: bigint;
    /**
     * @generated from protobuf field: bool need_guard = 3
     */
    needGuard: boolean;
    /**
     * @generated from protobuf field: bool strong_depend = 4
     */
    strongDepend: boolean;
    /**
     * @generated from protobuf field: bool need_group = 5
     */
    needGroup: boolean;
}
/**
 * @generated from protobuf message OfficialInfo
 */
export interface OfficialInfo {
    /**
     * @generated from protobuf field: int64 role = 1
     */
    role: bigint;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string desc = 3
     */
    desc: string;
    /**
     * @generated from protobuf field: int64 type = 4
     */
    type: bigint;
}
/**
 * @generated from protobuf message RiskCtrl
 */
export interface RiskCtrl {
    /**
     * @generated from protobuf field: int64 room_id = 1
     */
    roomId: bigint;
    /**
     * @generated from protobuf field: RiskPolicyEnum policy = 2
     */
    policy: RiskPolicyEnum;
}
/**
 * @generated from protobuf message RiskCtrlInfo
 */
export interface RiskCtrlInfo {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string face = 2
     */
    face: string;
}
/**
 * @generated from protobuf message RoomAnonCtrl
 */
export interface RoomAnonCtrl {
    /**
     * @generated from protobuf field: RoomAnonTypeEnum type = 1
     */
    type: RoomAnonTypeEnum;
}
/**
 * @generated from protobuf message Title
 */
export interface Title {
    /**
     * @generated from protobuf field: string old_title_css_id = 1
     */
    oldTitleCssId: string;
    /**
     * @generated from protobuf field: string title_css_id = 2
     */
    titleCssId: string;
}
/**
 * @generated from protobuf message TitleOption
 */
export interface TitleOption {
    /**
     * @generated from protobuf field: int64 room_id = 1
     */
    roomId: bigint;
    /**
     * @generated from protobuf field: bool strong_depend = 2
     */
    strongDepend: boolean;
}
/**
 * @generated from protobuf message UserHeadFrame
 */
export interface UserHeadFrame {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: string frame_img = 2
     */
    frameImg: string;
}
/**
 * @generated from protobuf message UserInfo
 */
export interface UserInfo {
    /**
     * @generated from protobuf field: int64 uid = 1
     */
    uid: bigint;
    /**
     * @generated from protobuf field: Base base = 2
     */
    base?: Base;
    /**
     * @generated from protobuf field: Medal medal = 3
     */
    medal?: Medal;
    /**
     * @generated from protobuf field: Wealth wealth = 4
     */
    wealth?: Wealth;
    /**
     * @generated from protobuf field: Title title = 5
     */
    title?: Title;
    /**
     * @generated from protobuf field: Guard guard = 6
     */
    guard?: Guard;
    /**
     * @generated from protobuf field: UserHeadFrame uhead_frame = 7
     */
    uheadFrame?: UserHeadFrame;
    /**
     * @generated from protobuf field: GuardLeader guard_leader = 8
     */
    guardLeader?: GuardLeader;
}
/**
 * @generated from protobuf message Wealth
 */
export interface Wealth {
    /**
     * @generated from protobuf field: int64 level = 1
     */
    level: bigint;
    /**
     * @generated from protobuf field: string dm_icon_key = 2
     */
    dmIconKey: string;
}
/**
 * @generated from protobuf message WealthOption
 */
export interface WealthOption {
    /**
     * @generated from protobuf field: int64 roomid = 1
     */
    roomid: bigint;
    /**
     * @generated from protobuf field: int64 view_uid = 2
     */
    viewUid: bigint;
    /**
     * @generated from protobuf field: int64 ruid = 3
     */
    ruid: bigint;
    /**
     * @generated from protobuf field: bool strong_depend = 4
     */
    strongDepend: boolean;
}
/**
 * `ONLINE_RANK_V3` cmd
 *
 * @generated from protobuf message GoldRankBroadcast
 */
export interface GoldRankBroadcast {
    /**
     * 排行类型
     * `gold-rank`: 高能用户(似乎不下发，记录缺失)
     * `online_rank`: 在线用户
     *
     * @generated from protobuf field: string rank_type = 1
     */
    rankType: string;
    /**
     * 高能榜
     *
     * @generated from protobuf field: repeated GoldRankBroadcast.GoldRankBrodcastItem list = 2
     */
    list: GoldRankBroadcast_GoldRankBrodcastItem[];
    /**
     * 在线榜
     *
     * @generated from protobuf field: repeated GoldRankBroadcast.GoldRankBrodcastItem online_list = 3
     */
    onlineList: GoldRankBroadcast_GoldRankBrodcastItem[];
}
/**
 * 单个排行数据
 *
 * @generated from protobuf message GoldRankBroadcast.GoldRankBrodcastItem
 */
export interface GoldRankBroadcast_GoldRankBrodcastItem {
    /**
     * 用户mid
     *
     * @generated from protobuf field: int64 uid = 1
     */
    uid: bigint;
    /**
     * 头像
     *
     * @generated from protobuf field: string face = 2
     */
    face: string;
    /**
     * 贡献值
     *
     * @generated from protobuf field: string score = 3
     */
    score: string;
    /**
     * 用户名称
     *
     * @generated from protobuf field: string uname = 4
     */
    uname: string;
    /**
     * 在榜单中的排名
     *
     * @generated from protobuf field: int64 rank = 5
     */
    rank: bigint;
    /**
     * @generated from protobuf field: int64 guard_level = 6
     */
    guardLevel: bigint;
    /**
     * @generated from protobuf field: bool is_mystery = 7
     */
    isMystery: boolean;
    /**
     * 用户信息
     *
     * @generated from protobuf field: UserInfo uinfo = 8
     */
    uinfo?: UserInfo;
}
/**
 * @generated from protobuf enum HaveMedalType
 */
export enum HaveMedalType {
    /**
     * @generated from protobuf enum value: Medal_Common = 0;
     */
    Medal_Common = 0,
    /**
     * @generated from protobuf enum value: Medal_Group = 1;
     */
    Medal_Group = 1
}
/**
 * @generated from protobuf enum MedalType
 */
export enum MedalType {
    /**
     * @generated from protobuf enum value: Medal_Wear = 0;
     */
    Medal_Wear = 0,
    /**
     * @generated from protobuf enum value: Medal_Spec = 1;
     */
    Medal_Spec = 1
}
/**
 * @generated from protobuf enum RiskPolicyEnum
 */
export enum RiskPolicyEnum {
    /**
     * @generated from protobuf enum value: RP_NORMAL = 0;
     */
    RP_NORMAL = 0,
    /**
     * @generated from protobuf enum value: RP_POLICY = 1;
     */
    RP_POLICY = 1,
    /**
     * @generated from protobuf enum value: RP_SILENCE = 2;
     */
    RP_SILENCE = 2,
    /**
     * @generated from protobuf enum value: RP_CNY = 3;
     */
    RP_CNY = 3,
    /**
     * @generated from protobuf enum value: RP_BIGEV = 4;
     */
    RP_BIGEV = 4
}
/**
 * @generated from protobuf enum RoomAnonTypeEnum
 */
export enum RoomAnonTypeEnum {
    /**
     * @generated from protobuf enum value: RA_ALL = 0;
     */
    RA_ALL = 0,
    /**
     * @generated from protobuf enum value: RA_With_Subject = 1;
     */
    RA_With_Subject = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class AccountInfo$Type extends MessageType<AccountInfo> {
    constructor() {
        super("AccountInfo", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "face", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AccountInfo>): AccountInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.face = "";
        if (value !== undefined)
            reflectionMergePartial<AccountInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AccountInfo): AccountInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string face */ 2:
                    message.face = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AccountInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string face = 2; */
        if (message.face !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.face);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AccountInfo
 */
export const AccountInfo = new AccountInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Base$Type extends MessageType<Base> {
    constructor() {
        super("Base", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "face", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name_color", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "is_mystery", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "risk_ctrl_info", kind: "message", T: () => RiskCtrlInfo },
            { no: 6, name: "origin_info", kind: "message", T: () => AccountInfo },
            { no: 7, name: "official_info", kind: "message", T: () => OfficialInfo },
            { no: 8, name: "name_color_str", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Base>): Base {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.face = "";
        message.nameColor = 0;
        message.isMystery = false;
        message.nameColorStr = "";
        if (value !== undefined)
            reflectionMergePartial<Base>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Base): Base {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string face */ 2:
                    message.face = reader.string();
                    break;
                case /* int32 name_color */ 3:
                    message.nameColor = reader.int32();
                    break;
                case /* bool is_mystery */ 4:
                    message.isMystery = reader.bool();
                    break;
                case /* RiskCtrlInfo risk_ctrl_info */ 5:
                    message.riskCtrlInfo = RiskCtrlInfo.internalBinaryRead(reader, reader.uint32(), options, message.riskCtrlInfo);
                    break;
                case /* AccountInfo origin_info */ 6:
                    message.originInfo = AccountInfo.internalBinaryRead(reader, reader.uint32(), options, message.originInfo);
                    break;
                case /* OfficialInfo official_info */ 7:
                    message.officialInfo = OfficialInfo.internalBinaryRead(reader, reader.uint32(), options, message.officialInfo);
                    break;
                case /* string name_color_str */ 8:
                    message.nameColorStr = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Base, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string face = 2; */
        if (message.face !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.face);
        /* int32 name_color = 3; */
        if (message.nameColor !== 0)
            writer.tag(3, WireType.Varint).int32(message.nameColor);
        /* bool is_mystery = 4; */
        if (message.isMystery !== false)
            writer.tag(4, WireType.Varint).bool(message.isMystery);
        /* RiskCtrlInfo risk_ctrl_info = 5; */
        if (message.riskCtrlInfo)
            RiskCtrlInfo.internalBinaryWrite(message.riskCtrlInfo, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* AccountInfo origin_info = 6; */
        if (message.originInfo)
            AccountInfo.internalBinaryWrite(message.originInfo, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* OfficialInfo official_info = 7; */
        if (message.officialInfo)
            OfficialInfo.internalBinaryWrite(message.officialInfo, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* string name_color_str = 8; */
        if (message.nameColorStr !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.nameColorStr);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Base
 */
export const Base = new Base$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BaseOption$Type extends MessageType<BaseOption> {
    constructor() {
        super("BaseOption", [
            { no: 1, name: "need_mystery", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "risk_ctrl", kind: "message", T: () => RiskCtrl },
            { no: 3, name: "room_anon_ctrl", kind: "message", T: () => RoomAnonCtrl },
            { no: 4, name: "risk_ctrl_handles", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<BaseOption>): BaseOption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.needMystery = false;
        message.riskCtrlHandles = [];
        if (value !== undefined)
            reflectionMergePartial<BaseOption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BaseOption): BaseOption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool need_mystery */ 1:
                    message.needMystery = reader.bool();
                    break;
                case /* RiskCtrl risk_ctrl */ 2:
                    message.riskCtrl = RiskCtrl.internalBinaryRead(reader, reader.uint32(), options, message.riskCtrl);
                    break;
                case /* RoomAnonCtrl room_anon_ctrl */ 3:
                    message.roomAnonCtrl = RoomAnonCtrl.internalBinaryRead(reader, reader.uint32(), options, message.roomAnonCtrl);
                    break;
                case /* repeated int32 risk_ctrl_handles */ 4:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.riskCtrlHandles.push(reader.int32());
                    else
                        message.riskCtrlHandles.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BaseOption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool need_mystery = 1; */
        if (message.needMystery !== false)
            writer.tag(1, WireType.Varint).bool(message.needMystery);
        /* RiskCtrl risk_ctrl = 2; */
        if (message.riskCtrl)
            RiskCtrl.internalBinaryWrite(message.riskCtrl, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* RoomAnonCtrl room_anon_ctrl = 3; */
        if (message.roomAnonCtrl)
            RoomAnonCtrl.internalBinaryWrite(message.roomAnonCtrl, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated int32 risk_ctrl_handles = 4; */
        if (message.riskCtrlHandles.length) {
            writer.tag(4, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.riskCtrlHandles.length; i++)
                writer.int32(message.riskCtrlHandles[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BaseOption
 */
export const BaseOption = new BaseOption$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Guard$Type extends MessageType<Guard> {
    constructor() {
        super("Guard", [
            { no: 1, name: "level", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "expired_str", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Guard>): Guard {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.level = 0n;
        message.expiredStr = "";
        if (value !== undefined)
            reflectionMergePartial<Guard>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Guard): Guard {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 level */ 1:
                    message.level = reader.int64().toBigInt();
                    break;
                case /* string expired_str */ 2:
                    message.expiredStr = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Guard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 level = 1; */
        if (message.level !== 0n)
            writer.tag(1, WireType.Varint).int64(message.level);
        /* string expired_str = 2; */
        if (message.expiredStr !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.expiredStr);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Guard
 */
export const Guard = new Guard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GuardLeader$Type extends MessageType<GuardLeader> {
    constructor() {
        super("GuardLeader", [
            { no: 1, name: "is_guard_leader", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GuardLeader>): GuardLeader {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isGuardLeader = false;
        if (value !== undefined)
            reflectionMergePartial<GuardLeader>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GuardLeader): GuardLeader {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_guard_leader */ 1:
                    message.isGuardLeader = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GuardLeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_guard_leader = 1; */
        if (message.isGuardLeader !== false)
            writer.tag(1, WireType.Varint).bool(message.isGuardLeader);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GuardLeader
 */
export const GuardLeader = new GuardLeader$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GuardLeaderOption$Type extends MessageType<GuardLeaderOption> {
    constructor() {
        super("GuardLeaderOption", [
            { no: 1, name: "ruid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "room_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GuardLeaderOption>): GuardLeaderOption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ruid = 0n;
        message.roomId = 0n;
        if (value !== undefined)
            reflectionMergePartial<GuardLeaderOption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GuardLeaderOption): GuardLeaderOption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 ruid */ 1:
                    message.ruid = reader.int64().toBigInt();
                    break;
                case /* int64 room_id */ 2:
                    message.roomId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GuardLeaderOption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 ruid = 1; */
        if (message.ruid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.ruid);
        /* int64 room_id = 2; */
        if (message.roomId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.roomId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GuardLeaderOption
 */
export const GuardLeaderOption = new GuardLeaderOption$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GuardOption$Type extends MessageType<GuardOption> {
    constructor() {
        super("GuardOption", [
            { no: 1, name: "ruid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "use_local_cache", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "strong_depend", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GuardOption>): GuardOption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ruid = 0n;
        message.useLocalCache = false;
        message.strongDepend = false;
        if (value !== undefined)
            reflectionMergePartial<GuardOption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GuardOption): GuardOption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 ruid */ 1:
                    message.ruid = reader.int64().toBigInt();
                    break;
                case /* bool use_local_cache */ 2:
                    message.useLocalCache = reader.bool();
                    break;
                case /* bool strong_depend */ 3:
                    message.strongDepend = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GuardOption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 ruid = 1; */
        if (message.ruid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.ruid);
        /* bool use_local_cache = 2; */
        if (message.useLocalCache !== false)
            writer.tag(2, WireType.Varint).bool(message.useLocalCache);
        /* bool strong_depend = 3; */
        if (message.strongDepend !== false)
            writer.tag(3, WireType.Varint).bool(message.strongDepend);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GuardOption
 */
export const GuardOption = new GuardOption$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Medal$Type extends MessageType<Medal> {
    constructor() {
        super("Medal", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "level", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "color_start", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "color_end", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "color_border", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "color", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "typ", kind: "enum", T: () => ["HaveMedalType", HaveMedalType] },
            { no: 9, name: "is_light", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 10, name: "ruid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 11, name: "guard_level", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 12, name: "score", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 13, name: "guard_icon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "honor_icon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "v2_medal_color_start", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "v2_medal_color_end", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "v2_medal_color_border", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "v2_medal_color_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "v2_medal_color_level", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "user_receive_count", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Medal>): Medal {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.level = 0n;
        message.colorStart = 0n;
        message.colorEnd = 0n;
        message.colorBorder = 0n;
        message.color = 0n;
        message.id = 0n;
        message.typ = 0;
        message.isLight = 0n;
        message.ruid = 0n;
        message.guardLevel = 0n;
        message.score = 0n;
        message.guardIcon = "";
        message.honorIcon = "";
        message.v2MedalColorStart = "";
        message.v2MedalColorEnd = "";
        message.v2MedalColorBorder = "";
        message.v2MedalColorText = "";
        message.v2MedalColorLevel = "";
        message.userReceiveCount = 0n;
        if (value !== undefined)
            reflectionMergePartial<Medal>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Medal): Medal {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* int64 level */ 2:
                    message.level = reader.int64().toBigInt();
                    break;
                case /* int64 color_start */ 3:
                    message.colorStart = reader.int64().toBigInt();
                    break;
                case /* int64 color_end */ 4:
                    message.colorEnd = reader.int64().toBigInt();
                    break;
                case /* int64 color_border */ 5:
                    message.colorBorder = reader.int64().toBigInt();
                    break;
                case /* int64 color */ 6:
                    message.color = reader.int64().toBigInt();
                    break;
                case /* int64 id */ 7:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* HaveMedalType typ */ 8:
                    message.typ = reader.int32();
                    break;
                case /* int64 is_light */ 9:
                    message.isLight = reader.int64().toBigInt();
                    break;
                case /* int64 ruid */ 10:
                    message.ruid = reader.int64().toBigInt();
                    break;
                case /* int64 guard_level */ 11:
                    message.guardLevel = reader.int64().toBigInt();
                    break;
                case /* int64 score */ 12:
                    message.score = reader.int64().toBigInt();
                    break;
                case /* string guard_icon */ 13:
                    message.guardIcon = reader.string();
                    break;
                case /* string honor_icon */ 14:
                    message.honorIcon = reader.string();
                    break;
                case /* string v2_medal_color_start */ 15:
                    message.v2MedalColorStart = reader.string();
                    break;
                case /* string v2_medal_color_end */ 16:
                    message.v2MedalColorEnd = reader.string();
                    break;
                case /* string v2_medal_color_border */ 17:
                    message.v2MedalColorBorder = reader.string();
                    break;
                case /* string v2_medal_color_text */ 18:
                    message.v2MedalColorText = reader.string();
                    break;
                case /* string v2_medal_color_level */ 19:
                    message.v2MedalColorLevel = reader.string();
                    break;
                case /* int64 user_receive_count */ 20:
                    message.userReceiveCount = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Medal, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* int64 level = 2; */
        if (message.level !== 0n)
            writer.tag(2, WireType.Varint).int64(message.level);
        /* int64 color_start = 3; */
        if (message.colorStart !== 0n)
            writer.tag(3, WireType.Varint).int64(message.colorStart);
        /* int64 color_end = 4; */
        if (message.colorEnd !== 0n)
            writer.tag(4, WireType.Varint).int64(message.colorEnd);
        /* int64 color_border = 5; */
        if (message.colorBorder !== 0n)
            writer.tag(5, WireType.Varint).int64(message.colorBorder);
        /* int64 color = 6; */
        if (message.color !== 0n)
            writer.tag(6, WireType.Varint).int64(message.color);
        /* int64 id = 7; */
        if (message.id !== 0n)
            writer.tag(7, WireType.Varint).int64(message.id);
        /* HaveMedalType typ = 8; */
        if (message.typ !== 0)
            writer.tag(8, WireType.Varint).int32(message.typ);
        /* int64 is_light = 9; */
        if (message.isLight !== 0n)
            writer.tag(9, WireType.Varint).int64(message.isLight);
        /* int64 ruid = 10; */
        if (message.ruid !== 0n)
            writer.tag(10, WireType.Varint).int64(message.ruid);
        /* int64 guard_level = 11; */
        if (message.guardLevel !== 0n)
            writer.tag(11, WireType.Varint).int64(message.guardLevel);
        /* int64 score = 12; */
        if (message.score !== 0n)
            writer.tag(12, WireType.Varint).int64(message.score);
        /* string guard_icon = 13; */
        if (message.guardIcon !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.guardIcon);
        /* string honor_icon = 14; */
        if (message.honorIcon !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.honorIcon);
        /* string v2_medal_color_start = 15; */
        if (message.v2MedalColorStart !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.v2MedalColorStart);
        /* string v2_medal_color_end = 16; */
        if (message.v2MedalColorEnd !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.v2MedalColorEnd);
        /* string v2_medal_color_border = 17; */
        if (message.v2MedalColorBorder !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.v2MedalColorBorder);
        /* string v2_medal_color_text = 18; */
        if (message.v2MedalColorText !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.v2MedalColorText);
        /* string v2_medal_color_level = 19; */
        if (message.v2MedalColorLevel !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.v2MedalColorLevel);
        /* int64 user_receive_count = 20; */
        if (message.userReceiveCount !== 0n)
            writer.tag(20, WireType.Varint).int64(message.userReceiveCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Medal
 */
export const Medal = new Medal$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MedalOption$Type extends MessageType<MedalOption> {
    constructor() {
        super("MedalOption", [
            { no: 1, name: "typ", kind: "enum", T: () => ["MedalType", MedalType] },
            { no: 2, name: "ruid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "need_guard", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "strong_depend", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "need_group", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<MedalOption>): MedalOption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.typ = 0;
        message.ruid = 0n;
        message.needGuard = false;
        message.strongDepend = false;
        message.needGroup = false;
        if (value !== undefined)
            reflectionMergePartial<MedalOption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MedalOption): MedalOption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* MedalType typ */ 1:
                    message.typ = reader.int32();
                    break;
                case /* int64 ruid */ 2:
                    message.ruid = reader.int64().toBigInt();
                    break;
                case /* bool need_guard */ 3:
                    message.needGuard = reader.bool();
                    break;
                case /* bool strong_depend */ 4:
                    message.strongDepend = reader.bool();
                    break;
                case /* bool need_group */ 5:
                    message.needGroup = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MedalOption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* MedalType typ = 1; */
        if (message.typ !== 0)
            writer.tag(1, WireType.Varint).int32(message.typ);
        /* int64 ruid = 2; */
        if (message.ruid !== 0n)
            writer.tag(2, WireType.Varint).int64(message.ruid);
        /* bool need_guard = 3; */
        if (message.needGuard !== false)
            writer.tag(3, WireType.Varint).bool(message.needGuard);
        /* bool strong_depend = 4; */
        if (message.strongDepend !== false)
            writer.tag(4, WireType.Varint).bool(message.strongDepend);
        /* bool need_group = 5; */
        if (message.needGroup !== false)
            writer.tag(5, WireType.Varint).bool(message.needGroup);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MedalOption
 */
export const MedalOption = new MedalOption$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OfficialInfo$Type extends MessageType<OfficialInfo> {
    constructor() {
        super("OfficialInfo", [
            { no: 1, name: "role", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "desc", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<OfficialInfo>): OfficialInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.role = 0n;
        message.title = "";
        message.desc = "";
        message.type = 0n;
        if (value !== undefined)
            reflectionMergePartial<OfficialInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OfficialInfo): OfficialInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 role */ 1:
                    message.role = reader.int64().toBigInt();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string desc */ 3:
                    message.desc = reader.string();
                    break;
                case /* int64 type */ 4:
                    message.type = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OfficialInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 role = 1; */
        if (message.role !== 0n)
            writer.tag(1, WireType.Varint).int64(message.role);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string desc = 3; */
        if (message.desc !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.desc);
        /* int64 type = 4; */
        if (message.type !== 0n)
            writer.tag(4, WireType.Varint).int64(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message OfficialInfo
 */
export const OfficialInfo = new OfficialInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RiskCtrl$Type extends MessageType<RiskCtrl> {
    constructor() {
        super("RiskCtrl", [
            { no: 1, name: "room_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "policy", kind: "enum", T: () => ["RiskPolicyEnum", RiskPolicyEnum] }
        ]);
    }
    create(value?: PartialMessage<RiskCtrl>): RiskCtrl {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roomId = 0n;
        message.policy = 0;
        if (value !== undefined)
            reflectionMergePartial<RiskCtrl>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RiskCtrl): RiskCtrl {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 room_id */ 1:
                    message.roomId = reader.int64().toBigInt();
                    break;
                case /* RiskPolicyEnum policy */ 2:
                    message.policy = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RiskCtrl, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 room_id = 1; */
        if (message.roomId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.roomId);
        /* RiskPolicyEnum policy = 2; */
        if (message.policy !== 0)
            writer.tag(2, WireType.Varint).int32(message.policy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RiskCtrl
 */
export const RiskCtrl = new RiskCtrl$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RiskCtrlInfo$Type extends MessageType<RiskCtrlInfo> {
    constructor() {
        super("RiskCtrlInfo", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "face", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RiskCtrlInfo>): RiskCtrlInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.face = "";
        if (value !== undefined)
            reflectionMergePartial<RiskCtrlInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RiskCtrlInfo): RiskCtrlInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string face */ 2:
                    message.face = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RiskCtrlInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string face = 2; */
        if (message.face !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.face);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RiskCtrlInfo
 */
export const RiskCtrlInfo = new RiskCtrlInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RoomAnonCtrl$Type extends MessageType<RoomAnonCtrl> {
    constructor() {
        super("RoomAnonCtrl", [
            { no: 1, name: "type", kind: "enum", T: () => ["RoomAnonTypeEnum", RoomAnonTypeEnum] }
        ]);
    }
    create(value?: PartialMessage<RoomAnonCtrl>): RoomAnonCtrl {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<RoomAnonCtrl>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RoomAnonCtrl): RoomAnonCtrl {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* RoomAnonTypeEnum type */ 1:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RoomAnonCtrl, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* RoomAnonTypeEnum type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RoomAnonCtrl
 */
export const RoomAnonCtrl = new RoomAnonCtrl$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Title$Type extends MessageType<Title> {
    constructor() {
        super("Title", [
            { no: 1, name: "old_title_css_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title_css_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Title>): Title {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.oldTitleCssId = "";
        message.titleCssId = "";
        if (value !== undefined)
            reflectionMergePartial<Title>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Title): Title {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string old_title_css_id */ 1:
                    message.oldTitleCssId = reader.string();
                    break;
                case /* string title_css_id */ 2:
                    message.titleCssId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Title, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string old_title_css_id = 1; */
        if (message.oldTitleCssId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.oldTitleCssId);
        /* string title_css_id = 2; */
        if (message.titleCssId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.titleCssId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Title
 */
export const Title = new Title$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TitleOption$Type extends MessageType<TitleOption> {
    constructor() {
        super("TitleOption", [
            { no: 1, name: "room_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "strong_depend", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TitleOption>): TitleOption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roomId = 0n;
        message.strongDepend = false;
        if (value !== undefined)
            reflectionMergePartial<TitleOption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TitleOption): TitleOption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 room_id */ 1:
                    message.roomId = reader.int64().toBigInt();
                    break;
                case /* bool strong_depend */ 2:
                    message.strongDepend = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TitleOption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 room_id = 1; */
        if (message.roomId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.roomId);
        /* bool strong_depend = 2; */
        if (message.strongDepend !== false)
            writer.tag(2, WireType.Varint).bool(message.strongDepend);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TitleOption
 */
export const TitleOption = new TitleOption$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserHeadFrame$Type extends MessageType<UserHeadFrame> {
    constructor() {
        super("UserHeadFrame", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "frame_img", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserHeadFrame>): UserHeadFrame {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.frameImg = "";
        if (value !== undefined)
            reflectionMergePartial<UserHeadFrame>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserHeadFrame): UserHeadFrame {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string frame_img */ 2:
                    message.frameImg = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserHeadFrame, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string frame_img = 2; */
        if (message.frameImg !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.frameImg);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserHeadFrame
 */
export const UserHeadFrame = new UserHeadFrame$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserInfo$Type extends MessageType<UserInfo> {
    constructor() {
        super("UserInfo", [
            { no: 1, name: "uid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "base", kind: "message", T: () => Base },
            { no: 3, name: "medal", kind: "message", T: () => Medal },
            { no: 4, name: "wealth", kind: "message", T: () => Wealth },
            { no: 5, name: "title", kind: "message", T: () => Title },
            { no: 6, name: "guard", kind: "message", T: () => Guard },
            { no: 7, name: "uhead_frame", kind: "message", T: () => UserHeadFrame },
            { no: 8, name: "guard_leader", kind: "message", T: () => GuardLeader }
        ]);
    }
    create(value?: PartialMessage<UserInfo>): UserInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uid = 0n;
        if (value !== undefined)
            reflectionMergePartial<UserInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserInfo): UserInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 uid */ 1:
                    message.uid = reader.int64().toBigInt();
                    break;
                case /* Base base */ 2:
                    message.base = Base.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* Medal medal */ 3:
                    message.medal = Medal.internalBinaryRead(reader, reader.uint32(), options, message.medal);
                    break;
                case /* Wealth wealth */ 4:
                    message.wealth = Wealth.internalBinaryRead(reader, reader.uint32(), options, message.wealth);
                    break;
                case /* Title title */ 5:
                    message.title = Title.internalBinaryRead(reader, reader.uint32(), options, message.title);
                    break;
                case /* Guard guard */ 6:
                    message.guard = Guard.internalBinaryRead(reader, reader.uint32(), options, message.guard);
                    break;
                case /* UserHeadFrame uhead_frame */ 7:
                    message.uheadFrame = UserHeadFrame.internalBinaryRead(reader, reader.uint32(), options, message.uheadFrame);
                    break;
                case /* GuardLeader guard_leader */ 8:
                    message.guardLeader = GuardLeader.internalBinaryRead(reader, reader.uint32(), options, message.guardLeader);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 uid = 1; */
        if (message.uid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.uid);
        /* Base base = 2; */
        if (message.base)
            Base.internalBinaryWrite(message.base, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* Medal medal = 3; */
        if (message.medal)
            Medal.internalBinaryWrite(message.medal, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* Wealth wealth = 4; */
        if (message.wealth)
            Wealth.internalBinaryWrite(message.wealth, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* Title title = 5; */
        if (message.title)
            Title.internalBinaryWrite(message.title, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* Guard guard = 6; */
        if (message.guard)
            Guard.internalBinaryWrite(message.guard, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* UserHeadFrame uhead_frame = 7; */
        if (message.uheadFrame)
            UserHeadFrame.internalBinaryWrite(message.uheadFrame, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* GuardLeader guard_leader = 8; */
        if (message.guardLeader)
            GuardLeader.internalBinaryWrite(message.guardLeader, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserInfo
 */
export const UserInfo = new UserInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Wealth$Type extends MessageType<Wealth> {
    constructor() {
        super("Wealth", [
            { no: 1, name: "level", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "dm_icon_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Wealth>): Wealth {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.level = 0n;
        message.dmIconKey = "";
        if (value !== undefined)
            reflectionMergePartial<Wealth>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Wealth): Wealth {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 level */ 1:
                    message.level = reader.int64().toBigInt();
                    break;
                case /* string dm_icon_key */ 2:
                    message.dmIconKey = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Wealth, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 level = 1; */
        if (message.level !== 0n)
            writer.tag(1, WireType.Varint).int64(message.level);
        /* string dm_icon_key = 2; */
        if (message.dmIconKey !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.dmIconKey);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Wealth
 */
export const Wealth = new Wealth$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WealthOption$Type extends MessageType<WealthOption> {
    constructor() {
        super("WealthOption", [
            { no: 1, name: "roomid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "view_uid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "ruid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "strong_depend", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<WealthOption>): WealthOption {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roomid = 0n;
        message.viewUid = 0n;
        message.ruid = 0n;
        message.strongDepend = false;
        if (value !== undefined)
            reflectionMergePartial<WealthOption>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WealthOption): WealthOption {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 roomid */ 1:
                    message.roomid = reader.int64().toBigInt();
                    break;
                case /* int64 view_uid */ 2:
                    message.viewUid = reader.int64().toBigInt();
                    break;
                case /* int64 ruid */ 3:
                    message.ruid = reader.int64().toBigInt();
                    break;
                case /* bool strong_depend */ 4:
                    message.strongDepend = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WealthOption, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 roomid = 1; */
        if (message.roomid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.roomid);
        /* int64 view_uid = 2; */
        if (message.viewUid !== 0n)
            writer.tag(2, WireType.Varint).int64(message.viewUid);
        /* int64 ruid = 3; */
        if (message.ruid !== 0n)
            writer.tag(3, WireType.Varint).int64(message.ruid);
        /* bool strong_depend = 4; */
        if (message.strongDepend !== false)
            writer.tag(4, WireType.Varint).bool(message.strongDepend);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message WealthOption
 */
export const WealthOption = new WealthOption$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GoldRankBroadcast$Type extends MessageType<GoldRankBroadcast> {
    constructor() {
        super("GoldRankBroadcast", [
            { no: 1, name: "rank_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "list", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GoldRankBroadcast_GoldRankBrodcastItem },
            { no: 3, name: "online_list", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GoldRankBroadcast_GoldRankBrodcastItem }
        ]);
    }
    create(value?: PartialMessage<GoldRankBroadcast>): GoldRankBroadcast {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rankType = "";
        message.list = [];
        message.onlineList = [];
        if (value !== undefined)
            reflectionMergePartial<GoldRankBroadcast>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GoldRankBroadcast): GoldRankBroadcast {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string rank_type */ 1:
                    message.rankType = reader.string();
                    break;
                case /* repeated GoldRankBroadcast.GoldRankBrodcastItem list */ 2:
                    message.list.push(GoldRankBroadcast_GoldRankBrodcastItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated GoldRankBroadcast.GoldRankBrodcastItem online_list */ 3:
                    message.onlineList.push(GoldRankBroadcast_GoldRankBrodcastItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GoldRankBroadcast, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string rank_type = 1; */
        if (message.rankType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.rankType);
        /* repeated GoldRankBroadcast.GoldRankBrodcastItem list = 2; */
        for (let i = 0; i < message.list.length; i++)
            GoldRankBroadcast_GoldRankBrodcastItem.internalBinaryWrite(message.list[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated GoldRankBroadcast.GoldRankBrodcastItem online_list = 3; */
        for (let i = 0; i < message.onlineList.length; i++)
            GoldRankBroadcast_GoldRankBrodcastItem.internalBinaryWrite(message.onlineList[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GoldRankBroadcast
 */
export const GoldRankBroadcast = new GoldRankBroadcast$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GoldRankBroadcast_GoldRankBrodcastItem$Type extends MessageType<GoldRankBroadcast_GoldRankBrodcastItem> {
    constructor() {
        super("GoldRankBroadcast.GoldRankBrodcastItem", [
            { no: 1, name: "uid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "face", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "score", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "uname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rank", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "guard_level", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "is_mystery", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "uinfo", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<GoldRankBroadcast_GoldRankBrodcastItem>): GoldRankBroadcast_GoldRankBrodcastItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uid = 0n;
        message.face = "";
        message.score = "";
        message.uname = "";
        message.rank = 0n;
        message.guardLevel = 0n;
        message.isMystery = false;
        if (value !== undefined)
            reflectionMergePartial<GoldRankBroadcast_GoldRankBrodcastItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GoldRankBroadcast_GoldRankBrodcastItem): GoldRankBroadcast_GoldRankBrodcastItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 uid */ 1:
                    message.uid = reader.int64().toBigInt();
                    break;
                case /* string face */ 2:
                    message.face = reader.string();
                    break;
                case /* string score */ 3:
                    message.score = reader.string();
                    break;
                case /* string uname */ 4:
                    message.uname = reader.string();
                    break;
                case /* int64 rank */ 5:
                    message.rank = reader.int64().toBigInt();
                    break;
                case /* int64 guard_level */ 6:
                    message.guardLevel = reader.int64().toBigInt();
                    break;
                case /* bool is_mystery */ 7:
                    message.isMystery = reader.bool();
                    break;
                case /* UserInfo uinfo */ 8:
                    message.uinfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.uinfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GoldRankBroadcast_GoldRankBrodcastItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 uid = 1; */
        if (message.uid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.uid);
        /* string face = 2; */
        if (message.face !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.face);
        /* string score = 3; */
        if (message.score !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.score);
        /* string uname = 4; */
        if (message.uname !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.uname);
        /* int64 rank = 5; */
        if (message.rank !== 0n)
            writer.tag(5, WireType.Varint).int64(message.rank);
        /* int64 guard_level = 6; */
        if (message.guardLevel !== 0n)
            writer.tag(6, WireType.Varint).int64(message.guardLevel);
        /* bool is_mystery = 7; */
        if (message.isMystery !== false)
            writer.tag(7, WireType.Varint).bool(message.isMystery);
        /* UserInfo uinfo = 8; */
        if (message.uinfo)
            UserInfo.internalBinaryWrite(message.uinfo, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GoldRankBroadcast.GoldRankBrodcastItem
 */
export const GoldRankBroadcast_GoldRankBrodcastItem = new GoldRankBroadcast_GoldRankBrodcastItem$Type();
